/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './index';
import * as import2 from '@angular/core/src/di/injector';
class SampleModuleInjector extends import0.NgModuleInjector<import1.SampleModule> {
  _SampleModule_0:import1.SampleModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.SampleModule {
    this._SampleModule_0 = new import1.SampleModule();
    return this._SampleModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.SampleModule)) { return this._SampleModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SampleModuleNgFactory:import0.NgModuleFactory<import1.SampleModule> = new import0.NgModuleFactory(SampleModuleInjector,import1.SampleModule);